### ISSUE TITLE
Expired Certificate on proget.makedeb.org

### ISSUE THREAD

**Issue by lxfontes** [makedeb/makedeb.org#38]
<img width="527" alt="Screenshot 2024-01-25 at 12 50 52 PM" src="https://github.com/makedeb/makedeb.org/assets/35205/f79cfe33-4546-473a-8a64-2ba21204d54e">
<img width="1164" alt="Screenshot 2024-01-25 at 12 50 47 PM" src="https://github.com/makedeb/makedeb.org/assets/35205/1798320d-bfaf-4b72-9c2a-bdd6bc2e4190">

**Comment by hwittenborn** [comment]
Thanks for the update @lxfontes, I got off school a bit ago and got notified of this by my service monitor. I'm not quite sure why the certificate expired, it should be being automatically renewed by a systems service on my system but that doesn't appear to be working for some reason.

This should be good now, and I'll be posting further incident resolution information in the [`makedeb: General` Matrix channel](https://docs.makedeb.org/support/obtaining-support/#matrix-rooms).
